version: 2

models:
  - name: stg_hicp
    columns:
      - name: country_code
        tests:
          - not_null
      - name: obs_value
        tests:
          - not_null

  - name: stg_gdp
    columns:
      - name: country_code
        tests:
          - not_null
      - name: obs_value
        tests:
          - not_null